FROM hadoop

ENV HBASE_HOME /hbase
ENV HBASE_CONF_DIR $HBASE_HOME/conf
ENV HBASE_MANAGES_ZK false
ENV ZOOKEEPER_HOME /zookeeper
ENV ZOOCFGDIR $ZOOKEEPER_HOME/conf
ENV ZOOBINDIR $ZOOKEEPER_HOME/bin
ENV ZOOKEEPER_PREFIX $ZOOKEEPER_HOME
ENV PATH $PATH:$HBASE_HOME/bin:$ZOOKEEPER_HOME/bin

# zookeeper port
EXPOSE 2182 2888 3888

# hbase web ui
EXPOSE 16010

# hbase rest api port
EXPOSE 8880 8885

ADD zookeeper-3.4.10 $ZOOKEEPER_HOME
ADD zkEnv.sh $ZOOBINDIR
ADD zoo.cfg $ZOOCFGDIR

ADD hbase-1.3.1 $HBASE_HOME
ADD hbase-env.sh $HBASE_CONF_DIR
ADD hbase-site.xml $HBASE_CONF_DIR
ADD regionservers $HBASE_CONF_DIR
ADD backup-masters $HBASE_CONF_DIR
ADD zoo.cfg $HBASE_CONF_DIR

VOLUME /data

ADD hbase.sh /
RUN chmod +x /hbase.sh

CMD ["/hbase.sh", "-bash"]
